// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16

package wasi_clocks_types

import ()

// A duration of time, in nanoseconds.
type Duration = uint64
