// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0-rc-2025-09-16
//     wasi:sockets@0.3.0-rc-2025-09-16

package wit_exports

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}
