// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     example:sdk

package wasi_cli_types

import ()

const (
	// Input/output error
	ErrorCode_Io uint8 = 0
	// Invalid or incomplete multibyte or wide character
	ErrorCode_IllegalByteSequence uint8 = 1
	// Broken pipe
	ErrorCode_Pipe uint8 = 2
)

type ErrorCode = uint8
