// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     foo:baz@0.1.0
//     wasi:io@0.2.8
//     wasi:clocks@0.2.8
//     wasi:filesystem@0.2.8
//     wasi:sockets@0.2.8
//     wasi:random@0.2.8
//     wasi:cli@0.2.8
//     wasi:config@0.2.0-rc.1
//     wasi:logging@0.1.0-draft
//     wasi:http@0.2.8
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     bytecodealliance:pkg@0.1.0

package foo_baz_store

import (
        witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
"unsafe"
"runtime"
)


//go:wasmimport foo:baz/store@0.1.0 get
func wasm_import_get(arg0 uintptr, arg1 uint32, arg2 uintptr) 


func Get(key string) string {
        pinner := &runtime.Pinner{}
defer pinner.Unpin()

        returnArea := uintptr(witRuntime.Allocate(pinner, (2*4), 4))
        utf8 := unsafe.Pointer(unsafe.StringData(key))
pinner.Pin(utf8)
wasm_import_get(uintptr(utf8), uint32(len(key)), returnArea)
value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
result := value;
return result

}
