// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     example:sdk

package wasi_sockets_ip_name_lookup

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"pkg/bindings/imports/wasi_sockets_types"
	"runtime"
	"unsafe"
)

type IpAddress = wasi_sockets_types.IpAddress

const (
	// Access denied.
	//
	// POSIX equivalent: EACCES, EPERM
	ErrorCode_AccessDenied uint8 = 0
	// `name` is a syntactically invalid domain name or IP address.
	//
	// POSIX equivalent: EINVAL
	ErrorCode_InvalidArgument uint8 = 1
	// Name does not exist or has no suitable associated IP addresses.
	//
	// POSIX equivalent: EAI_NONAME, EAI_NODATA, EAI_ADDRFAMILY
	ErrorCode_NameUnresolvable uint8 = 2
	// A temporary failure in name resolution occurred.
	//
	// POSIX equivalent: EAI_AGAIN
	ErrorCode_TemporaryResolverFailure uint8 = 3
	// A permanent failure in name resolution occurred.
	//
	// POSIX equivalent: EAI_FAIL
	ErrorCode_PermanentResolverFailure uint8 = 4
	// A catch-all for errors not captured by the existing variants.
	// Implementations can use this to extend the error type without
	// breaking existing code.
	ErrorCode_Other uint8 = 5
)

// Lookup error codes.
type ErrorCode struct {
	tag   uint8
	value any
}

func (self ErrorCode) Tag() uint8 {
	return self.tag
}

func (self ErrorCode) Other() witTypes.Option[string] {
	if self.tag != ErrorCode_Other {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Option[string])
}

func MakeErrorCodeAccessDenied() ErrorCode {
	return ErrorCode{ErrorCode_AccessDenied, nil}
}
func MakeErrorCodeInvalidArgument() ErrorCode {
	return ErrorCode{ErrorCode_InvalidArgument, nil}
}
func MakeErrorCodeNameUnresolvable() ErrorCode {
	return ErrorCode{ErrorCode_NameUnresolvable, nil}
}
func MakeErrorCodeTemporaryResolverFailure() ErrorCode {
	return ErrorCode{ErrorCode_TemporaryResolverFailure, nil}
}
func MakeErrorCodePermanentResolverFailure() ErrorCode {
	return ErrorCode{ErrorCode_PermanentResolverFailure, nil}
}
func MakeErrorCodeOther(value witTypes.Option[string]) ErrorCode {
	return ErrorCode{ErrorCode_Other, value}
}

//go:wasmimport wasi:sockets/ip-name-lookup@0.3.0 [async-lower]resolve-addresses
func wasm_import_resolve_addresses(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func ResolveAddresses(name string) witTypes.Result[[]wasi_sockets_types.IpAddress, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_resolve_addresses(uintptr(utf8), uint32(len(name)), returnArea)))
	var result1 witTypes.Result[[]wasi_sockets_types.IpAddress, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]wasi_sockets_types.IpAddress, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*18)
			var variant wasi_sockets_types.IpAddress
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
			case 0:

				variant = wasi_sockets_types.MakeIpAddressIpv4(witTypes.Tuple4[uint8, uint8, uint8, uint8]{F0: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 2)))), F1: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 3)))), F2: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))), F3: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 5))))})

			case 1:

				variant = wasi_sockets_types.MakeIpAddressIpv6(witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]{F0: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 2)))), F1: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))), F2: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 6)))), F3: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), F4: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 10)))), F5: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12)))), F6: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 14)))), F7: uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16))))})

			default:
				panic("unreachable")
			}

			result = append(result, variant)
		}

		result1 = witTypes.Ok[[]wasi_sockets_types.IpAddress, ErrorCode](result)
	case 1:
		var variant0 ErrorCode
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant0 = MakeErrorCodeAccessDenied()

		case 1:

			variant0 = MakeErrorCodeInvalidArgument()

		case 2:

			variant0 = MakeErrorCodeNameUnresolvable()

		case 3:

			variant0 = MakeErrorCodeTemporaryResolverFailure()

		case 4:

			variant0 = MakeErrorCodePermanentResolverFailure()

		case 5:
			var option witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				option = witTypes.None[string]()
			case 1:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))

				option = witTypes.Some[string](value)
			default:
				panic("unreachable")
			}

			variant0 = MakeErrorCodeOther(option)

		default:
			panic("unreachable")
		}

		result1 = witTypes.Err[[]wasi_sockets_types.IpAddress, ErrorCode](variant0)
	default:
		panic("unreachable")
	}

	return result1

}
